// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type DebugLog struct {
	ID        int64
	Level     string
	Message   string
	CreatedAt string
}

type JsonlEntry struct {
	SessionName string
	SessionPath string
	Uuid        string
	Timestamp   string
}

type MonitorHeartbeat struct {
	ID        int64
	Version   string
	UpdatedAt string
}

type Session struct {
	Name           string
	Path           string
	Status         string
	AgentSessionID string
	AgentTool      string
	CreatedAt      string
	UpdatedAt      string
}
