// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const deleteJsonlEntries = `-- name: DeleteJsonlEntries :exec
DELETE FROM jsonl_entries WHERE session_name = ? AND session_path = ?
`

type DeleteJsonlEntriesParams struct {
	SessionName string
	SessionPath string
}

func (q *Queries) DeleteJsonlEntries(ctx context.Context, arg DeleteJsonlEntriesParams) error {
	_, err := q.db.ExecContext(ctx, deleteJsonlEntries, arg.SessionName, arg.SessionPath)
	return err
}

const deleteOldDebugLog = `-- name: DeleteOldDebugLog :exec
DELETE FROM debug_log WHERE created_at < ?
`

func (q *Queries) DeleteOldDebugLog(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, deleteOldDebugLog, createdAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE name = ? AND path = ?
`

type DeleteSessionParams struct {
	Name string
	Path string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.Name, arg.Path)
	return err
}

const getLatestJsonlEntry = `-- name: GetLatestJsonlEntry :one
SELECT uuid, timestamp FROM jsonl_entries
WHERE session_name = ? AND session_path = ?
ORDER BY timestamp DESC
LIMIT 1
`

type GetLatestJsonlEntryParams struct {
	SessionName string
	SessionPath string
}

type GetLatestJsonlEntryRow struct {
	Uuid      string
	Timestamp string
}

func (q *Queries) GetLatestJsonlEntry(ctx context.Context, arg GetLatestJsonlEntryParams) (GetLatestJsonlEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestJsonlEntry, arg.SessionName, arg.SessionPath)
	var i GetLatestJsonlEntryRow
	err := row.Scan(&i.Uuid, &i.Timestamp)
	return i, err
}

const getMonitorHeartbeat = `-- name: GetMonitorHeartbeat :one
SELECT version, updated_at FROM monitor_heartbeat WHERE id = 1
`

type GetMonitorHeartbeatRow struct {
	Version   string
	UpdatedAt string
}

func (q *Queries) GetMonitorHeartbeat(ctx context.Context) (GetMonitorHeartbeatRow, error) {
	row := q.db.QueryRowContext(ctx, getMonitorHeartbeat)
	var i GetMonitorHeartbeatRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}

const getSessionStatus = `-- name: GetSessionStatus :one
SELECT status FROM sessions WHERE name = ? AND path = ?
`

type GetSessionStatusParams struct {
	Name string
	Path string
}

func (q *Queries) GetSessionStatus(ctx context.Context, arg GetSessionStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSessionStatus, arg.Name, arg.Path)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertDebugLog = `-- name: InsertDebugLog :exec
INSERT INTO debug_log (level, message, created_at) VALUES (?, ?, ?)
`

type InsertDebugLogParams struct {
	Level     string
	Message   string
	CreatedAt string
}

func (q *Queries) InsertDebugLog(ctx context.Context, arg InsertDebugLogParams) error {
	_, err := q.db.ExecContext(ctx, insertDebugLog, arg.Level, arg.Message, arg.CreatedAt)
	return err
}

const listSessions = `-- name: ListSessions :many
SELECT name, path, status, agent_session_id, agent_tool, updated_at FROM sessions
`

type ListSessionsRow struct {
	Name           string
	Path           string
	Status         string
	AgentSessionID string
	AgentTool      string
	UpdatedAt      string
}

func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.Name,
			&i.Path,
			&i.Status,
			&i.AgentSessionID,
			&i.AgentTool,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentSessionID = `-- name: UpdateAgentSessionID :exec
UPDATE sessions SET agent_session_id = ?, updated_at = ?
WHERE name = ? AND path = ?
`

type UpdateAgentSessionIDParams struct {
	AgentSessionID string
	UpdatedAt      string
	Name           string
	Path           string
}

func (q *Queries) UpdateAgentSessionID(ctx context.Context, arg UpdateAgentSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentSessionID,
		arg.AgentSessionID,
		arg.UpdatedAt,
		arg.Name,
		arg.Path,
	)
	return err
}

const updateAgentTool = `-- name: UpdateAgentTool :exec
UPDATE sessions SET agent_tool = ?, updated_at = ?
WHERE name = ? AND path = ?
`

type UpdateAgentToolParams struct {
	AgentTool string
	UpdatedAt string
	Name      string
	Path      string
}

func (q *Queries) UpdateAgentTool(ctx context.Context, arg UpdateAgentToolParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentTool,
		arg.AgentTool,
		arg.UpdatedAt,
		arg.Name,
		arg.Path,
	)
	return err
}

const updateSessionStatusIfUnchanged = `-- name: UpdateSessionStatusIfUnchanged :exec
UPDATE sessions SET status = ?, updated_at = ?
WHERE name = ? AND path = ? AND status = ?
`

type UpdateSessionStatusIfUnchangedParams struct {
	Status    string
	UpdatedAt string
	Name      string
	Path      string
	Status_2  string
}

func (q *Queries) UpdateSessionStatusIfUnchanged(ctx context.Context, arg UpdateSessionStatusIfUnchangedParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatusIfUnchanged,
		arg.Status,
		arg.UpdatedAt,
		arg.Name,
		arg.Path,
		arg.Status_2,
	)
	return err
}

const upsertJsonlEntry = `-- name: UpsertJsonlEntry :exec
INSERT INTO jsonl_entries (session_name, session_path, uuid, timestamp)
VALUES (?, ?, ?, ?)
ON CONFLICT (session_name, session_path, uuid) DO NOTHING
`

type UpsertJsonlEntryParams struct {
	SessionName string
	SessionPath string
	Uuid        string
	Timestamp   string
}

func (q *Queries) UpsertJsonlEntry(ctx context.Context, arg UpsertJsonlEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertJsonlEntry,
		arg.SessionName,
		arg.SessionPath,
		arg.Uuid,
		arg.Timestamp,
	)
	return err
}

const upsertMonitorHeartbeat = `-- name: UpsertMonitorHeartbeat :exec
INSERT INTO monitor_heartbeat (id, version, updated_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    version = excluded.version,
    updated_at = excluded.updated_at
`

type UpsertMonitorHeartbeatParams struct {
	Version   string
	UpdatedAt string
}

func (q *Queries) UpsertMonitorHeartbeat(ctx context.Context, arg UpsertMonitorHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonitorHeartbeat, arg.Version, arg.UpdatedAt)
	return err
}

const upsertSessionStatus = `-- name: UpsertSessionStatus :exec
INSERT INTO sessions (name, path, status, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (name, path) DO UPDATE SET
    status = excluded.status,
    updated_at = excluded.updated_at
`

type UpsertSessionStatusParams struct {
	Name      string
	Path      string
	Status    string
	UpdatedAt string
}

func (q *Queries) UpsertSessionStatus(ctx context.Context, arg UpsertSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionStatus,
		arg.Name,
		arg.Path,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
